Add feature/check method
intarocrm/rest-api-client pull request #185
Opened 2023-12-18 10:02 UTC by Chupocabra

2023-12-18 10:11 UTC, max-baranikov requested changes

2023-12-18 10:11 UTC, max-baranikov commented on src/ResourceGroup/Api.php
> +     *     $response = $client->api->featuresCheck();
В примере не передается $request

2023-12-18 10:11 UTC, max-baranikov commented on tests/src/ResourceGroup/ApiTest.php
> +        $mock = static::createUnversionedApiMockBuilder('features/check');
Здесь нужно использовать `createApiMockBuilder`

2023-12-20 12:23 UTC, Neur0toxine requested changes

2023-12-20 12:23 UTC, Neur0toxine commented on src/ResourceGroup/Features.php
> +     *     $response = $client->api->featuresCheck($request);
Неверный код в примере, тут будет
```php
$client->features->check($request);
```

2023-12-20 12:53 UTC, merged