updated method TelephonyCallEvent
intarocrm/rest-api-client pull request #88
Opened 2020-09-07 11:25 UTC by SoldierOfHeart

2020-09-07 11:43 UTC, Neur0toxine requested changes

2020-09-07 11:43 UTC, Neur0toxine commented on lib/RetailCrm/Methods/V3/Telephony.php
> +     * @param string $callExternalId'
Лишняя одинарная кавычка после названия переменной.

2020-09-07 11:43 UTC, Neur0toxine commented on lib/RetailCrm/Methods/V3/Telephony.php
> +     * @param array $userIds
Здесь стоит выровнять название так же, как сделано в остальных тегах. Это можно выполнить автоматически в PHPStorm выделив весь докблок, и нажав Ctrl+Alt+L.

2020-09-07 11:48 UTC, muxx commented
Может добавить php-cs-fixer в проект, чтобы не тратить время ревьювера на такие вещи

2020-09-08 07:14 UTC, Neur0toxine approved these changes

2020-09-09 08:29 UTC, Neur0toxine requested changes

2020-09-09 08:29 UTC, Neur0toxine commented on tests/RetailCrm/Tests/Methods/Version4/ApiClientTelephonyTest.php
> +
Лишний перевод строки.

2020-09-09 08:29 UTC, Neur0toxine commented on tests/RetailCrm/Tests/Methods/Version4/ApiClientTelephonyTest.php
> +        $client = static::getMockedApiClient($stub);
Перед этим вызовом нужен перевод строки.

2020-09-09 08:52 UTC, Neur0toxine approved these changes

2020-09-09 09:51 UTC, merged